[[main]]
    # Top-level menu entry
    identifier = "work"
    name = "Work"
    url = "/projects/"
    weight = 1

[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    parent = "work"
    weight = 1

[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    parent = "work"
    weight = 2

[[main]]
    # Top-level menu entry
    identifier = "writing"
    name = "Writing"
    url = "/posts/"
    weight = 4

[[main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    parent = "writing"
    weight = 4

[[main]]
    identifier = "data-science"
    name = "Data Science"
    url = "/data-science/"
    # url = "/posts/data-science/" # Remove url param from subsection/_index.md frontmatter to use full permalink
    parent = "writing"
    weight = 5

[[main]]
    identifier = "neuroscience"
    name = "Neuroscience"
    url = "/neuroscience/"
    # url = "/posts/neuroscience/" # Remove url param from subsection/_index.md frontmatter to use full permalink
    parent = "writing"
    weight = 6

[[main]]
    identifier = "philosophy"
    name = "Philosophy"
    url = "/philosophy/"
    # url = "/posts/philosophy/" # Remove url param from subsection/_index.md frontmatter to use full permalink
    parent = "writing"
    weight = 7

[[main]]
    identifier = "economics"
    name = "Economics"
    url = "/economics/"
    # url = "/posts/economics/" # Remove url param from subsection/_index.md frontmatter to use full permalink
    parent = "writing"
    weight = 8

[[main]]
    # Top-level menu entry
    identifier = "explore"
    name = "Explore"
    url = "/categories/"
    weight = 6

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    parent = "explore"
    weight = 6

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    parent = "explore"
    weight = 7

[[main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    parent = "explore"
    weight = 8

[[main]]
    identifier = "project-type"
    name = "Project Types"
    url = "/project-types/"
    parent = "explore"
    weight = 9